name: Deploy TIS

on:
  push:
    branches:
      - "staging"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: build app
        run: |
          pnpm install
          pnpm run build

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: build again
        run: |
          pnpm install
          pnpm run build
          rm -rf node_modules

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist

      - name: Copy build folder to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.DEPLOY_HOST_STAGING }}
          username: ${{ secrets.USERNAME }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          localPath: "./dist"
          remotePath: "/home/ubuntu/staging/frontend/"
